apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: datadog-agent-deployment
  name: agent
  namespace: datadog
spec:
  ports:
    - name: dogstatsdport
      port: 8125
    - name: traceport
      port: 8126
  selector:
    app.kubernetes.io/name: datadog-agent-deployment
